[phases.setup]
nixPkgs = ['python311', 'postgresql']

[phases.install]
cmds = ['python -m pip install -r requirements.txt']

[phases.build]
cmds = ['python manage.py collectstatic --noinput', 'python manage.py migrate']

[start]
cmd = 'gunicorn cymaticspro.wsgi'