# nixpacks.toml
[phases.setup]
aptPkgs = ["python3", "python3-pip", "python3-venv", "build-essential", "python3-dev"]

[phases.install]
cmds = ["python -m venv /app/venv"]

[phases.build]
cmds = [
    "source /app/venv/bin/activate",
    "cd cymaticswork",
    "pip install --no-cache-dir -r requirements.txt",
    "python manage.py collectstatic --noinput",
    "python manage.py migrate --noinput"
]

[start]
cmd = "cd cymaticswork && source /app/venv/bin/activate && gunicorn cymaticspro.wsgi --log-file -"