[phases.setup]
aptPkgs = ['python3', 'python3-pip', 'python3-venv']

[phases.build]
cmds = [
  "python -m venv /app/venv",
  "source /app/venv/bin/activate",
  "cd cymaticswork",
  "pip install -r requirements.txt",
  "python manage.py collectstatic --noinput",
  "python manage.py migrate --noinput"
]

[start]
cmd = "gunicorn cymaticspro.wsgi --log-file -"