[build]
builder = "nixpacks"
buildCommand = "python -m pip install --upgrade pip && cd cymaticswork && pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate --noinput"

[deploy]
startCommand = "cd cymaticswork && gunicorn cymaticspro.wsgi --log-file -"
restartPolicyType = "on_failure"