# Generated by Django 5.1 on 2024-11-02 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymaticsapp', '0071_remove_project_out_comp_remove_project_out_num_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalendarEvent',
        ),
        migrations.AlterField(
            model_name='entertainment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cymaticsapp.client'),
        ),
    ]
