# Generated by Django 5.1 on 2024-12-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymaticsapp', '0072_delete_calendarevent_alter_entertainment_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=50),
        ),
    ]
